import React from 'react';
import {Html5Audio, interpolate, Sequence, staticFile} from 'remotion';

// Generated by scripts/generate-audio.py
type Sfx =
	| 'whoosh-soft'
	| 'whoosh-in'
	| 'whoosh-big'
	| 'whoosh-out'
	| 'whoosh-pan'
	| 'pop'
	| 'pop-high'
	| 'tick'
	| 'tap'
	| 'shimmer'
	| 'sparkle'
	| 'thump'
	| 'scan'
	| 'typing'
	| 'chime'
	| 'rise'
	| 'reverse-swell'
	| 'logo-hit';

type Cue = {at: number; sfx: Sfx; volume: number; rate?: number};

/**
 * Every sound effect, on the global 30fps timeline (see TIMELINE in PlanteaPromo.tsx).
 * Volumes are linear gain on top of the music bed.
 */
export const CUES: Cue[] = [
	// Intro: "Another" lands, thumbnails swing in on the arc
	{at: 0, sfx: 'whoosh-in', volume: 0.35},
	...[14, 16, 17, 19, 20, 22, 24, 25, 27].map(
		(at, i): Cue => ({at, sfx: 'tick', volume: 0.16, rate: 0.9 + (i % 4) * 0.08}),
	),
	{at: 21, sfx: 'whoosh-soft', volume: 0.22},
	{at: 26, sfx: 'whoosh-soft', volume: 0.18, rate: 1.15},

	// Cards collapse into the gap, room card grows to full frame
	{at: 34, sfx: 'whoosh-out', volume: 0.3},
	{at: 41, sfx: 'pop', volume: 0.35},
	{at: 44, sfx: 'whoosh-big', volume: 0.55},
	{at: 58, sfx: 'thump', volume: 0.45},

	// Room: plant glows, Analyze button assembles, camera push, tap
	{at: 72, sfx: 'shimmer', volume: 0.35},
	{at: 79, sfx: 'pop-high', volume: 0.3},
	{at: 82, sfx: 'tick', volume: 0.2, rate: 1.2},
	{at: 87, sfx: 'pop', volume: 0.28},
	{at: 96, sfx: 'whoosh-in', volume: 0.4, rate: 0.85},
	{at: 120, sfx: 'tap', volume: 0.7},
	{at: 136, sfx: 'whoosh-out', volume: 0.35},

	// Scanning
	{at: 140, sfx: 'whoosh-soft', volume: 0.3},
	{at: 146, sfx: 'scan', volume: 0.45},
	{at: 158, sfx: 'typing', volume: 0.3},

	// Diagnosis ready + dashboard build
	{at: 194, sfx: 'chime', volume: 0.55},
	{at: 198, sfx: 'sparkle', volume: 0.2},
	{at: 216, sfx: 'pop', volume: 0.3},
	{at: 220, sfx: 'pop', volume: 0.26, rate: 1.1},
	{at: 224, sfx: 'pop', volume: 0.24, rate: 1.2},
	{at: 226, sfx: 'pop-high', volume: 0.16},
	{at: 229, sfx: 'pop-high', volume: 0.15, rate: 1.1},
	{at: 232, sfx: 'pop-high', volume: 0.14, rate: 1.2},
	{at: 234, sfx: 'rise', volume: 0.22},
	{at: 258, sfx: 'whoosh-out', volume: 0.3},

	// Healthy rooms pan
	{at: 264, sfx: 'whoosh-pan', volume: 0.4},

	// Tagline wipe + "alive"
	{at: 301, sfx: 'whoosh-in', volume: 0.45, rate: 1.1},
	{at: 314, sfx: 'sparkle', volume: 0.35},

	// Logo
	{at: 324, sfx: 'reverse-swell', volume: 0.5},
	{at: 337, sfx: 'logo-hit', volume: 0.85},
];

export const SoundDesign: React.FC = () => (
	<>
		<Html5Audio
			src={staticFile('audio/music.wav')}
			// Duck the bed slightly under the logo hit so it lands.
			volume={(f) =>
				interpolate(f, [330, 338], [0.55, 0.38], {
					extrapolateLeft: 'clamp',
					extrapolateRight: 'clamp',
				})
			}
		/>
		{CUES.map((cue, i) => (
			<Sequence key={i} from={cue.at} name={`sfx: ${cue.sfx}`} layout="none">
				<Html5Audio
					src={staticFile(`audio/${cue.sfx}.wav`)}
					volume={cue.volume}
					playbackRate={cue.rate ?? 1}
				/>
			</Sequence>
		))}
	</>
);
